### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Kirby' not found

### ISSUE THREAD

**Issue by matthiasott** [kerli81/kirby-securedpages#4] opened 2020-05-21 15:47 UTC
When I install kirby-securedpages via Composer, I get an error:

**Fatal error:** Uncaught Error: Class 'Kirby' not found in […]/mzur/kirby-uniform/config.php:3

Installing only kirby-uniform works fine. I also already tried a fresh `composer install`. 
My Kirby version is 3.3.6.

Any help is much apprechiated. 🤗

**Comment by kerli81** [comment] 2021-01-01 18:38
I cannot reproduce it. Will close the issue. If it is still there, please let me know!

**Closed as completed by kerli81** 2021-01-01 18:38 UTC
